version: "3"
services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-alpine
  #   volumes:
  #     - "./default.conf:/etc/nginx/conf.d/default.conf"
  #   environment:
  #     - NGINX_HOST=walking.com
  #     - NGINX_PORT=80
  # veda:
  #   image: celestialbeing13/veda
  #   container_name: veda
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env.docker
  #   environment:
  #     - REDIS_URL=redis://redis
  #   depends_on:
  #     - redis
  #   volumes:
  #     - veda_data:/var/lib/veda/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: always
#   后面要补上 flutter前端
#   flutter:
volumes:
  redis_data:
    driver: local
  veda_data:
    driver: local
