version: "3"
services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-alpine
  #   volumes:
  #     - "./default.conf:/etc/nginx/conf.d/default.conf"
  #   environment:
  #     - NGINX_HOST=walking.com
  #     - NGINX_PORT=80
  actixwebsocket:
    image: warriorsfly/actixwebsocket
    container_name: actix-websocket-server
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://message-stream
    depends_on:
      - message-stream

  message-stream:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: always
#   后面要补上 flutter前端
#   application:
volumes:
  redis_data:
    driver: local
